pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Praveen2197/YourRepoName.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean compile'  // Use 'sh' if Linux agent
            }
        }

        stage('Run Multi-Device Test') {
            steps {
                bat 'mvn test -Dtest=AllDeviceAutomationUS'  // Replace with your actual test class
            }
        }
    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml'
            archiveArtifacts artifacts: '**/target/**/*.log, **/videos/*.mp4', fingerprint: true
        }
    }
}
